Added chm build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,12 +44,49 @@ jobs:
     - name: Build modelviewer
       run: msbuild MvProject.sln -property:Platform=x64 -property:Configuration=Release
 
+    - name: Install htmlhelp
+      run: |
+        curl -L -O http://web.archive.org/web/20160201063255/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
+        cmd /c start /wait .\htmlhelp.exe /q /c /t:$(Get-Location)\tmp
+        $file = "$(Get-Location)\tmp\htmlhelp.inf"
+        (Get-Content $file) | Foreach-Object { $_ `
+          -replace '^BeginPrompt',                                               ';;BeginPrompt' `
+          -replace '^EndPrompt',                                                 ';;EndPrompt' `
+          -replace '^49000=CustomLDID49000, 1',                                  '49000=CustomLDID49000, 5' `
+          -replace '^"hhupd.exe',                                                ';;hhupd.exe' `
+          -replace '^DefaultInstallDir="C:\\Program Files\\HTML Help Workshop"', 'DefaultInstallDir="%ProgramFiles%\\HTML Help Workshop"'
+        } | Set-Content $file
+        cmd /c start /wait .\tmp\setup.exe
+        Remove-Item -Recurse -Force .\tmp
+        Remove-Item -Recurse -Force .\htmlhelp.exe
+        # the next line doesn't seem to work (supposed to set the path)
+        # echo 'C:\Program Files (x86)\HTML Help Workshop' >> $GITHUB_PATH
+
+    - name: Compile chm
+      shell: bash
+      run: |
+        pushd Help
+        # hhc returns 1 on success
+        set +e
+        'C:\Program Files (x86)\HTML Help Workshop\hhc' mvmf6.hhp | tee mvmf6.out
+        status=${PIPESTATUS[0]}
+        set -e
+        if [ "$status" -eq 1 ]; then
+          echo "[OK]"
+          exit 0
+        else
+          echo "[FAILED]"
+          exit 1
+        fi
+        popd
+
     - name: Build mvmf6.zip
       run: |
         mkdir mvmf6
         Push-Location mvmf6
         Copy-Item ..\ModelViewer\x64\Release\mvmf6.exe .
         Copy-Item ..\mv\x64\Release\mv.dll .
+        Copy-Item ..\Help\mvmf6.chm .
         Copy-Item C:\VTK6.0.0_build64\bin\Release\vtkalglib-6.0.dll .
         Copy-Item C:\VTK6.0.0_build64\bin\Release\vtkCommonComputationalGeometry-6.0.dll .
         Copy-Item C:\VTK6.0.0_build64\bin\Release\vtkCommonCore-6.0.dll .
