testing cache merge

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,260 +15,240 @@ env:
 
 jobs:
 
-  vtk:
-    runs-on: windows-2016
-
-    steps:
-
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Cache vtk-6.3.0
-      id: cache-vtk-6-3-0
-      uses: actions/cache@v2
-      with:
-        path: C:\VTK-6.3.0-vs2017-x64
-        key: vtk-6.3.0-vs2017-x64-${{hashFiles('./misc/CMakePresets.json')}}
-
-    - name: Download vtk-6.3.0
-      if: steps.cache-vtk-6-3-0.outputs.cache-hit != 'true'
-      shell: pwsh
-      run: |
-        curl -L -O "https://github.com/Kitware/VTK/archive/refs/tags/v6.3.0.zip"
-        Get-FileHash .\v6.3.0.zip
-        cd C:\
-        7z x ${{github.workspace}}\v6.3.0.zip
-        rm ${{github.workspace}}\v6.3.0.zip
-
-    - name: Build vtk-6.3.0
-      if: steps.cache-vtk-6-3-0.outputs.cache-hit != 'true'
-      shell: pwsh
-      run: |
-        cp misc\CMakePresets.json C:\VTK-6.3.0\.
-        cd C:\VTK-6.3.0
-        cmake --preset vs2017
-        cmake --build --preset vs2017 --config debug
-        cmake --build --preset vs2017 --config release
-        cmake --install C:/VTK-6.3.0-vs2017-x64-build --prefix C:/VTK-6.3.0-vs2017-x64 --config debug
-        cmake --install C:/VTK-6.3.0-vs2017-x64-build --prefix C:/VTK-6.3.0-vs2017-x64 --config release
-        7z a ${{ github.workspace }}\vtk-6.3.0-vs2017-x64.7z C:\VTK-6.3.0-vs2017-x64
-
-    - name: upload-artifact 7z
-      if: steps.cache-vtk-6-3-0.outputs.cache-hit != 'true'
-      uses: actions/upload-artifact@v2
-      with:
-        name: vtk-6.3.0-vs2017-x64.7z
-        path: ${{ github.workspace }}/vtk-6.3.0-vs2017-x64.7z
-
-    - name: upload-artifact CMakeCache.txt
-      if: steps.cache-vtk-6-3-0.outputs.cache-hit != 'true'
-      uses: actions/upload-artifact@v2
-      with:
-        name: CMakeCache.txt
-        path: C:/VTK-6.3.0-vs2017-x64-build/CMakeCache.txt
-
   build:
     runs-on: windows-2019
+    needs: [cache-vtk]
 
     steps:
 
-    - name: Checkout
-      uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
 
-    - name: Cache vtk
-      id: cache-vtk
-      uses: actions/cache@v2
-      with:
-        path: |
-          C:\VTK6.0.0
-          C:\VTK6.0.0_build64
-        key: ${{runner.os}}-vtk-${{env.VTK_VERSION}}
+      - name: Check cache before
+        shell: pwsh
+        run: |
+          dir c:\vtk-6.3.0-vs2017-x64
+          dir c:\vtk-6.3.0-vs2017-x64\bin
+          dir c:\vtk-6.3.0-vs2017-x64\include
 
-    - name: Download and install vtk
-      if: steps.cache-vtk.outputs.cache-hit != 'true'
-      shell: pwsh
-      run: |
-        pip install gdown
-        gdown https://drive.google.com/uc?id=1FHn0dSghDXuVt3OvxrxtJP4KYtLap9be
-        7z x -oC:\ vtk6.zip
-        Remove-Item vtk6.zip
+      - name: Cache vtk
+        id: cache-vtk
+        uses: actions/cache@v2
+        with:
+          path: ${{env.instdir}}
+          key: ${{runner.os}}-vtk ## -${{hashFiles('.github/workflows/build-vtk.yml, misc/CMakePresets.json')}}
 
-    - name: Install htmlhelp
-      run: |
-        curl -L -O http://web.archive.org/web/20160201063255/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
-        cmd /c start /wait .\htmlhelp.exe /q /c /t:$(Get-Location)\tmp
-        # These changes allow htmlhelp to be installed without user input
-        $file = "$(Get-Location)\tmp\htmlhelp.inf"
-        (Get-Content $file) | Foreach-Object { $_ `
-          -replace '^BeginPrompt',                                               ';;BeginPrompt' `
-          -replace '^EndPrompt',                                                 ';;EndPrompt' `
-          -replace '^49000=CustomLDID49000, 1',                                  '49000=CustomLDID49000, 5' `
-          -replace '^"hhupd.exe',                                                ';;hhupd.exe' `
-          -replace '^DefaultInstallDir="C:\\Program Files\\HTML Help Workshop"', 'DefaultInstallDir="%ProgramFiles%\\HTML Help Workshop"'
-        } | Set-Content $file
-        cmd /c start /wait .\tmp\setup.exe
-        Remove-Item -Recurse -Force .\tmp
-        Remove-Item -Recurse -Force .\htmlhelp.exe
-        # the next line doesn't seem to work (supposed to set the path)
-        # echo 'C:\Program Files (x86)\HTML Help Workshop' >> $GITHUB_PATH
+      - name: Check cache
+        shell: pwsh
+        run: |
+          dir c:\vtk-6.3.0-vs2017-x64
+          dir c:\vtk-6.3.0-vs2017-x64\bin
+          dir c:\vtk-6.3.0-vs2017-x64\include
 
-    - name: Compile chm
-      shell: bash
-      run: |
-        pushd Help
-        # hhc returns 1 on success
-        set +e
-        'C:\Program Files (x86)\HTML Help Workshop\hhc' mvmf6.hhp | tee mvmf6.out
-        status=${PIPESTATUS[0]}
-        set -e
-        if [ "$status" -eq 1 ]; then
-          echo "[OK]"
-          exit 0
-        else
-          echo "[FAILED]"
-          exit 1
-        fi
-        popd
 
-    - name: Export next mvmf6 version
-      run: |
-        # create headers dictionary
-        $h = @{"Authorization" = "token ${{secrets.GITHUB_TOKEN}}"}
 
-        try {
-            $response = Invoke-WebRequest -Uri ${{env.RELEASES_URL}}/latest -Headers $h -Method GET
-            $json = $response.Content | ConvertFrom-Json
-            $tag_name = $json.tag_name
-        }
-        catch {
-            # none so far
-            $tag_name = "0.0"
-        }
+  # build:
+  #   runs-on: windows-2019
 
-        $next_version = "0.0.0"
-        if ($tag_name -match '(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)(?:\.(?<patch>0|[1-9]\d*))?$') {
-            if ($Matches.ContainsKey('patch')) {
-              $patch = 1 + $Matches['patch']
-            }
-            else {
-              $patch = 0
-            }
-            $next_version = $Matches['major'] + "." + $Matches['minor'] + "." + $patch
-        }
-        Write-Output "NEXT_VERSION=$next_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+  #   steps:
 
-    # - name: Configure vs2017
-    #   shell: pwsh
-    #   run: cmake --preset vs2017
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
 
-    # - name: Build vs2017
-    #   shell: pwsh
-    #   run: cmake --build _vs2017 --config release
+  #   - name: Cache vtk
+  #     id: cache-vtk
+  #     uses: actions/cache@v2
+  #     with:
+  #       path: |
+  #         C:\VTK6.0.0
+  #         C:\VTK6.0.0_build64
+  #       key: ${{runner.os}}-vtk-${{env.VTK_VERSION}}
 
-    # - name: Install vs2017
-    #   shell: pwsh
-    #   run: cmake --install _vs2017 --prefix mvmf6-${{env.NEXT_VERSION}}-vs2017 --config release
+  #   - name: Download and install vtk
+  #     if: steps.cache-vtk.outputs.cache-hit != 'true'
+  #     shell: pwsh
+  #     run: |
+  #       pip install gdown
+  #       gdown https://drive.google.com/uc?id=1FHn0dSghDXuVt3OvxrxtJP4KYtLap9be
+  #       7z x -oC:\ vtk6.zip
+  #       Remove-Item vtk6.zip
 
-    # - name: Build mvmf6-vs2017-x.x.x.zip
-    #   run: |
-    #     Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2017\bin\.
-    #     7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2017.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2017\
+  #   - name: Install htmlhelp
+  #     run: |
+  #       curl -L -O http://web.archive.org/web/20160201063255/http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
+  #       cmd /c start /wait .\htmlhelp.exe /q /c /t:$(Get-Location)\tmp
+  #       # These changes allow htmlhelp to be installed without user input
+  #       $file = "$(Get-Location)\tmp\htmlhelp.inf"
+  #       (Get-Content $file) | Foreach-Object { $_ `
+  #         -replace '^BeginPrompt',                                               ';;BeginPrompt' `
+  #         -replace '^EndPrompt',                                                 ';;EndPrompt' `
+  #         -replace '^49000=CustomLDID49000, 1',                                  '49000=CustomLDID49000, 5' `
+  #         -replace '^"hhupd.exe',                                                ';;hhupd.exe' `
+  #         -replace '^DefaultInstallDir="C:\\Program Files\\HTML Help Workshop"', 'DefaultInstallDir="%ProgramFiles%\\HTML Help Workshop"'
+  #       } | Set-Content $file
+  #       cmd /c start /wait .\tmp\setup.exe
+  #       Remove-Item -Recurse -Force .\tmp
+  #       Remove-Item -Recurse -Force .\htmlhelp.exe
+  #       # the next line doesn't seem to work (supposed to set the path)
+  #       # echo 'C:\Program Files (x86)\HTML Help Workshop' >> $GITHUB_PATH
 
-    - name: Build mvmf6-vs2017-x.x.x.zip
-      run: |
-        # Testing multiple asset upload (only htmlhelp file)
-        mkdir mvmf6-${{env.NEXT_VERSION}}-vs2017
-        mkdir mvmf6-${{env.NEXT_VERSION}}-vs2017\bin
-        Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2017\bin\.
-        7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2017.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2017\
+  #   - name: Compile chm
+  #     shell: bash
+  #     run: |
+  #       pushd Help
+  #       # hhc returns 1 on success
+  #       set +e
+  #       'C:\Program Files (x86)\HTML Help Workshop\hhc' mvmf6.hhp | tee mvmf6.out
+  #       status=${PIPESTATUS[0]}
+  #       set -e
+  #       if [ "$status" -eq 1 ]; then
+  #         echo "[OK]"
+  #         exit 0
+  #       else
+  #         echo "[FAILED]"
+  #         exit 1
+  #       fi
+  #       popd
 
-    - name: Configure vs2019
-      shell: pwsh
-      run: cmake --preset vs2019
+  #   - name: Export next mvmf6 version
+  #     run: |
+  #       # create headers dictionary
+  #       $h = @{"Authorization" = "token ${{secrets.GITHUB_TOKEN}}"}
 
-    - name: Build vs2019
-      shell: pwsh
-      run: cmake --build _vs2019 --config release
+  #       try {
+  #           $response = Invoke-WebRequest -Uri ${{env.RELEASES_URL}}/latest -Headers $h -Method GET
+  #           $json = $response.Content | ConvertFrom-Json
+  #           $tag_name = $json.tag_name
+  #       }
+  #       catch {
+  #           # none so far
+  #           $tag_name = "0.0"
+  #       }
 
-    - name: Install vs2019
-      shell: pwsh
-      run: cmake --install _vs2019 --prefix mvmf6-${{env.NEXT_VERSION}}-vs2019 --config release
+  #       $next_version = "0.0.0"
+  #       if ($tag_name -match '(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)(?:\.(?<patch>0|[1-9]\d*))?$') {
+  #           if ($Matches.ContainsKey('patch')) {
+  #             $patch = 1 + $Matches['patch']
+  #           }
+  #           else {
+  #             $patch = 0
+  #           }
+  #           $next_version = $Matches['major'] + "." + $Matches['minor'] + "." + $patch
+  #       }
+  #       Write-Output "NEXT_VERSION=$next_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
 
-    - name: Build mvmf6-vs2019-x.x.x.zip
-      run: |
-        Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2019\bin\.
-        7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2019.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2019\
+  #   # - name: Configure vs2017
+  #   #   shell: pwsh
+  #   #   run: cmake --preset vs2017
 
-    - name: Create release
-      run: |
-        # store new commit
-        $target_commitish = (git log -n1 --format=format:"%H")
+  #   # - name: Build vs2017
+  #   #   shell: pwsh
+  #   #   run: cmake --build _vs2017 --config release
 
-        if (! ($env:NEXT_VERSION -match "^(?<major>0|[1-9]\d*)\.(?<minor>[0|1-9]\d*)\.(?<patch>[0|1-9]\d*)$") ) {
-          throw "Bad version"
-        }
-        $version = $env:NEXT_VERSION
+  #   # - name: Install vs2017
+  #   #   shell: pwsh
+  #   #   run: cmake --install _vs2017 --prefix mvmf6-${{env.NEXT_VERSION}}-vs2017 --config release
 
-        # create headers dictionary
-        $h = @{"Authorization" = "token ${{secrets.GITHUB_TOKEN}}"}
+  #   # - name: Build mvmf6-vs2017-x.x.x.zip
+  #   #   run: |
+  #   #     Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2017\bin\.
+  #   #     7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2017.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2017\
 
-        $releases_url = "${{env.releases_url}}"
+  #   - name: Build mvmf6-vs2017-x.x.x.zip
+  #     run: |
+  #       # Testing multiple asset upload (only htmlhelp file)
+  #       mkdir mvmf6-${{env.NEXT_VERSION}}-vs2017
+  #       mkdir mvmf6-${{env.NEXT_VERSION}}-vs2017\bin
+  #       Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2017\bin\.
+  #       7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2017.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2017\
 
-        # create release
-        # POST /repos/{owner}/{repo}/releases
-        # see https://docs.github.com/en/rest/reference/repos#create-a-release
-        #
-        $create = @{
-          "tag_name"         = "$env:NEXT_VERSION"
-          "target_commitish" = "$target_commitish"
-          "name"             = "Model Viewer for Modflow 6 Version " + $version
-          "body"             = "Model Viewer for Modflow 6 Version " + $version
-          "draft"            = $true
-          # "prerelease"       = $true
-        }
-        $create_json = $create | ConvertTo-Json
-        $release = Invoke-WebRequest -Uri $releases_url -Headers $h -Method POST -Body $create_json
+  #   - name: Configure vs2019
+  #     shell: pwsh
+  #     run: cmake --preset vs2019
 
-        # upload artifact (asset)
-        # POST /repos/{owner}/{repo}/releases/{release_id}/assets
-        # see https://docs.github.com/en/rest/reference/repos#upload-a-release-asset
-        #
-        $upload_uri = ($release.Content | ConvertFrom-Json).upload_url
-        if (! ($upload_uri -match  "(.*)\{\?name,label\}") ) {
-          # expecting URI{?name,label}
-          # ie https://uploads.github.com/repos/MODFLOW-USGS/modelviewer-mf6/releases/24058628/assets{?name,label}
-          throw "Bad upload_url"
-        }
+  #   - name: Build vs2019
+  #     shell: pwsh
+  #     run: cmake --build _vs2019 --config release
 
-        # vs2017
-        $upload_uri = $Matches[1] + "?name=mvmf6-$version-vs2017.zip"
-        $h["Content-type"] = "application/zip"
-        $bytes = [System.IO.File]::ReadAllBytes("mvmf6-$version-vs2017.zip")
-        $upload = Invoke-WebRequest -Uri $upload_uri -Headers $h -Method POST -Body $bytes
+  #   - name: Install vs2019
+  #     shell: pwsh
+  #     run: cmake --install _vs2019 --prefix mvmf6-${{env.NEXT_VERSION}}-vs2019 --config release
 
-        # vs2019
-        $upload_uri = $Matches[1] + "?name=mvmf6-$version-vs2019.zip"
-        $h["Content-type"] = "application/zip"
-        $bytes = [System.IO.File]::ReadAllBytes("mvmf6-$version-vs2019.zip")
-        $upload = Invoke-WebRequest -Uri $upload_uri -Headers $h -Method POST -Body $bytes
+  #   - name: Build mvmf6-vs2019-x.x.x.zip
+  #     run: |
+  #       Copy-Item .\Help\mvmf6.chm mvmf6-${{env.NEXT_VERSION}}-vs2019\bin\.
+  #       7z a -tzip mvmf6-${{env.NEXT_VERSION}}-vs2019.zip .\mvmf6-${{env.NEXT_VERSION}}-vs2019\
 
-        # update release
-        # PATCH /repos/{owner}/{repo}/releases/{release_id}
-        # see https://docs.github.com/en/rest/reference/repos#update-a-release
-        #
-        $release_id = ($release.Content | ConvertFrom-Json).id
-        $h.Remove("Content-type")
-        $update = @{ "draft" = $false }
-        $update_json = $update | ConvertTo-Json
-        $release = Invoke-WebRequest -Uri "$releases_url/$release_id" -Headers $h -Method PATCH -Body $update_json
+  #   - name: Create release
+  #     run: |
+  #       # store new commit
+  #       $target_commitish = (git log -n1 --format=format:"%H")
 
-        # display download url vs2017
-        Write-Output "$((($release.Content | ConvertFrom-Json).assets[0]).browser_download_url)"
-        Get-FileHash "mvmf6-$version-vs2017.zip"
-        Remove-Item mvmf6-$version-vs2017.zip
+  #       if (! ($env:NEXT_VERSION -match "^(?<major>0|[1-9]\d*)\.(?<minor>[0|1-9]\d*)\.(?<patch>[0|1-9]\d*)$") ) {
+  #         throw "Bad version"
+  #       }
+  #       $version = $env:NEXT_VERSION
 
-        # display download url vs2019
-        Write-Output "$((($release.Content | ConvertFrom-Json).assets[1]).browser_download_url)"
-        Get-FileHash "mvmf6-$version-vs2019.zip"
-        Remove-Item mvmf6-$version-vs2019.zip
+  #       # create headers dictionary
+  #       $h = @{"Authorization" = "token ${{secrets.GITHUB_TOKEN}}"}
+
+  #       $releases_url = "${{env.releases_url}}"
+
+  #       # create release
+  #       # POST /repos/{owner}/{repo}/releases
+  #       # see https://docs.github.com/en/rest/reference/repos#create-a-release
+  #       #
+  #       $create = @{
+  #         "tag_name"         = "$env:NEXT_VERSION"
+  #         "target_commitish" = "$target_commitish"
+  #         "name"             = "Model Viewer for Modflow 6 Version " + $version
+  #         "body"             = "Model Viewer for Modflow 6 Version " + $version
+  #         "draft"            = $true
+  #         # "prerelease"       = $true
+  #       }
+  #       $create_json = $create | ConvertTo-Json
+  #       $release = Invoke-WebRequest -Uri $releases_url -Headers $h -Method POST -Body $create_json
+
+  #       # upload artifact (asset)
+  #       # POST /repos/{owner}/{repo}/releases/{release_id}/assets
+  #       # see https://docs.github.com/en/rest/reference/repos#upload-a-release-asset
+  #       #
+  #       $upload_uri = ($release.Content | ConvertFrom-Json).upload_url
+  #       if (! ($upload_uri -match  "(.*)\{\?name,label\}") ) {
+  #         # expecting URI{?name,label}
+  #         # ie https://uploads.github.com/repos/MODFLOW-USGS/modelviewer-mf6/releases/24058628/assets{?name,label}
+  #         throw "Bad upload_url"
+  #       }
+
+  #       # vs2017
+  #       $upload_uri = $Matches[1] + "?name=mvmf6-$version-vs2017.zip"
+  #       $h["Content-type"] = "application/zip"
+  #       $bytes = [System.IO.File]::ReadAllBytes("mvmf6-$version-vs2017.zip")
+  #       $upload = Invoke-WebRequest -Uri $upload_uri -Headers $h -Method POST -Body $bytes
+
+  #       # vs2019
+  #       $upload_uri = $Matches[1] + "?name=mvmf6-$version-vs2019.zip"
+  #       $h["Content-type"] = "application/zip"
+  #       $bytes = [System.IO.File]::ReadAllBytes("mvmf6-$version-vs2019.zip")
+  #       $upload = Invoke-WebRequest -Uri $upload_uri -Headers $h -Method POST -Body $bytes
+
+  #       # update release
+  #       # PATCH /repos/{owner}/{repo}/releases/{release_id}
+  #       # see https://docs.github.com/en/rest/reference/repos#update-a-release
+  #       #
+  #       $release_id = ($release.Content | ConvertFrom-Json).id
+  #       $h.Remove("Content-type")
+  #       $update = @{ "draft" = $false }
+  #       $update_json = $update | ConvertTo-Json
+  #       $release = Invoke-WebRequest -Uri "$releases_url/$release_id" -Headers $h -Method PATCH -Body $update_json
+
+  #       # display download url vs2017
+  #       Write-Output "$((($release.Content | ConvertFrom-Json).assets[0]).browser_download_url)"
+  #       Get-FileHash "mvmf6-$version-vs2017.zip"
+  #       Remove-Item mvmf6-$version-vs2017.zip
+
+  #       # display download url vs2019
+  #       Write-Output "$((($release.Content | ConvertFrom-Json).assets[1]).browser_download_url)"
+  #       Get-FileHash "mvmf6-$version-vs2019.zip"
+  #       Remove-Item mvmf6-$version-vs2019.zip
 
